import re
import traceback
from deoplete.source.base import Base

# ------------------------------- KEYWORD -------------------------------------------------------------------------
rails_keywords = [
    '_get', '_insert_callbacks', '_layout_for', '_normalize_args', '_normalize_callback_options',
    '_normalize_options', '_prepare_context', '_process_options', '_render_to_body_with_renderer',
    '_render_with_renderer_method_name', '_routes', '_routes_context', '_set_detail', '_set_wrapper_options',
    '_to_partial_path', '_url_for_modules', '_with_routes', 'abort', 'abstract!', 'abstract_class?',
    'abstract_railtie?', 'accept', 'accept?', 'accept_header', 'accepts', 'accepts_nested_attributes_for',
    'accessed_fields', 'accessor', 'acronym', 'action', 'action_cable_meta_tag', 'action_has_layout?',
    'action_methods', 'action_name', 'active?', 'active_connection?', 'active_connections?', 'acts_like?',
    'acts_like_date?', 'acts_like_string?', 'acts_like_time?', 'adapter_name', 'add', 'add_belongs_to',
    'add_bind', 'add_channel', 'add_child', 'add_column', 'add_delivery_method', 'add_event_subscriber',
    'add_filter', 'add_flash_types', 'add_foreign_key', 'add_index', 'add_reference', 'add_renderer',
    'add_shebang_option!', 'add_silencer', 'add_source', 'add_subscriber', 'add_tags', 'add_timestamps',
    'add_transaction_record', 'added?', 'advance', 'after', 'after_action', 'after_bundle', 'after_class_unload',
    'after_commit', 'after_create_commit', 'after_destroy_commit', 'after_enqueue', 'after_initialize',
    'after_perform', 'after_rollback', 'after_subscribe', 'after_teardown', 'after_unsubscribe',
    'after_update_commit', 'after_validation', 'aggregated_results', 'ago', 'alert', 'alias_attribute',
    'all', 'all?', 'all_day', 'all_helpers_from_path', 'all_month', 'all_paths', 'all_quarter', 'all_week',
    'all_year', 'allowed_index_name_length', 'analyze', 'analyze_later', 'analyzed?', 'annotations',
    'announce', 'anonymous?', 'any', 'any?', 'any_authenticity_token_valid?', 'any_templates?', 'any_waiting?',
    'api_dir', 'api_main', 'api_only!', 'api_only?', 'app', 'app_generators', 'app_middleware', 'append',
    'append_after_action', 'append_around_action', 'append_before_action', 'append_features',
    'append_info_to_payload', 'append_view_path', 'application', 'application_name', 'application_trace',
    'arguments', 'around_action', 'around_enqueue', 'around_perform', 'as_json', 'assert_changes',
    'assert_class_method', 'assert_difference', 'assert_directory', 'assert_emails', 'assert_enqueued_email_with',
    'assert_enqueued_emails', 'assert_enqueued_jobs', 'assert_enqueued_with', 'assert_field_default_value',
    'assert_field_type', 'assert_file', 'assert_generates', 'assert_instance_method', 'assert_method',
    'assert_migration', 'assert_no_changes', 'assert_no_difference', 'assert_no_directory',
    'assert_no_emails', 'assert_no_enqueued_emails', 'assert_no_enqueued_jobs', 'assert_no_file',
    'assert_no_migration', 'assert_no_performed_jobs', 'assert_not', 'assert_nothing_raised',
    'assert_performed_jobs', 'assert_performed_with', 'assert_recognizes', 'assert_redirected_to',
    'assert_response', 'assert_routing', 'assert_template', 'assert_valid_keys', 'assert_valid_value',
    'asset_path', 'asset_url', 'assets_manifest', 'assign_attributes', 'assigns', 'assoc', 'assume_migrated_upto_version',
    'at', 'at_beginning_of_day', 'at_beginning_of_hour', 'at_beginning_of_minute', 'at_beginning_of_month',
    'at_beginning_of_quarter', 'at_beginning_of_week', 'at_beginning_of_year', 'at_end_of_day',
    'at_end_of_hour', 'at_end_of_minute', 'at_end_of_month', 'at_end_of_quarter', 'at_end_of_week',
    'at_end_of_year', 'at_midday', 'at_middle_of_day', 'at_midnight', 'at_noon', 'at_with_coercion',
    'at_without_coercion', 'atom_feed', 'atomic_write', 'attach', 'attach_to', 'attached?', 'attachment',
    'attachments', 'attr_internal', 'attr_internal_accessor', 'attr_internal_reader', 'attr_internal_writer',
    'attr_readonly', 'attribute', 'attribute_alias', 'attribute_alias?', 'attribute_before_last_save',
    'attribute_change_to_be_saved', 'attribute_for_inspect', 'attribute_in_database', 'attribute_method?',
    'attribute_method_affix', 'attribute_method_prefix', 'attribute_method_suffix', 'attribute_missing',
    'attribute_names', 'attribute_present?', 'attributes', 'attributes_before_type_cast', 'attributes_for_hash',
    'attributes_in_database', 'attributes_names', 'audio?', 'audio_path', 'audio_tag', 'audio_url',
    'auth_param', 'auth_scheme', 'authenticate', 'authenticate_or_request_with_http_basic',
    'authenticate_or_request_with_http_digest', 'authenticate_or_request_with_http_token',
    'authenticate_with_http_basic', 'authenticate_with_http_digest', 'authenticate_with_http_token',
    'authentication_header', 'authentication_request', 'authorization', 'auto_discovery_link_tag',
    'autoload', 'autoload_at', 'autoload_once', 'autoload_once_paths', 'autoload_paths', 'autoload_under',
    'autoloads', 'available_action?', 'average', 'await_commit', 'await_sent', 'backend', 'backtrace_cleaner',
    'banner', 'base', 'base_class', 'base_name', 'base_root', 'beat', 'becomes', 'becomes!', 'before', 'before_action',
    'before_class_unload', 'before_configuration', 'before_eager_load', 'before_enqueue', 'before_initialize',
    'before_perform', 'before_subscribe', 'before_unsubscribe', 'before_validation', 'begin_db_transaction',
    'begin_isolated_db_transaction', 'beginning_of_day', 'beginning_of_hour', 'beginning_of_minute',
    'beginning_of_month', 'beginning_of_quarter', 'beginning_of_week', 'beginning_of_year',
    'behavior', 'belongs_to', 'belongs_to?', 'benchmark', 'between?', 'bigserial', 'bin', 'bin_when_updating',
    'binary?', 'bind', 'bit', 'bit_varying', 'blank?', 'blob', 'block_all_mixed_content', 'block_format',
    'body', 'body_parts', 'box', 'broadcast', 'broadcast_to', 'broadcaster_for', 'build', 'build_after_upload',
    'build_queue', 'build_response', 'build_stack', 'bulk_change_table', 'button', 'button_tag', 'button_to',
    'byte', 'bytes', 'cache', 'cache_fixtures', 'cache_for_connection', 'cache_fragment_name', 'cache_if',
    'cache_key', 'cache_key_with_version', 'cache_message', 'cache_store', 'cache_template_loading',
    'cache_unless', 'cache_version', 'cached_fixtures', 'calculate', 'calculate_ip', 'call', 'call_app',
    'camelcase', 'camelize', 'capify!', 'capitalize', 'capture', 'cast', 'cast_value', 'cattr_accessor',
    'cattr_reader', 'cattr_writer', 'cdata_block', 'cdata_section', 'change', 'change_column', 'change_column_comment',
    'change_column_default', 'change_column_null', 'change_default', 'change_table', 'change_table_comment',
    'changed', 'changed?', 'changed_attribute_names_to_save', 'changed_attributes', 'changed_for_autosave?',
    'changed_in_place?', 'changes', 'changes_applied', 'changes_to_save', 'channel_name', 'characters',
    'charset', 'charset_current', 'check_box', 'check_box_tag', 'check_class_collision', 'check_pending!',
    'check_protected_environments!', 'check_schema_file', 'check_target_version', 'checkin',
    'checkout', 'children', 'cidr', 'circle', 'citext', 'civil_from_format', 'class', 'class_attribute',
    'class_eval', 'class_methods', 'class_name', 'class_path', 'classify', 'clean', 'cleanup', 'cleanup_view_runtime',
    'clear', 'clear!', 'clear_action_methods!', 'clear_active_connections!', 'clear_all_connections!',
    'clear_attribute_changes', 'clear_cache', 'clear_cache!', 'clear_changes_information', 'clear_data_source_cache!',
    'clear_helpers', 'clear_query_cache', 'clear_reloadable_connections', 'clear_reloadable_connections!',
    'clear_validators!', 'client_min_messages', 'clone', 'clone_empty', 'close', 'code', 'code_and_name',
    'collation', 'collation_current', 'collection', 'collection_check_boxes', 'collection_radio_buttons',
    'collection_select', 'color', 'color_field', 'color_field_tag', 'colorize_logging', 'column',
    'column_defaults', 'column_exists?', 'column_for_attribute', 'column_name_length', 'column_names',
    'columns', 'columns_hash', 'columns_per_multicolumn_index', 'columns_per_table', 'combined_fragment_cache_key',
    'command_name', 'command_type', 'commit', 'commit!', 'commit_db_transaction', 'commit_flash',
    'committed?', 'compact', 'compact!', 'comparable_time', 'compare_with_coercion', 'compare_with_real_token',
    'compare_without_coercion', 'compile_methods!', 'complete', 'complete!', 'completed?', 'component_root_dir',
    'compose', 'composed_of', 'compress', 'compute_asset_extname', 'compute_asset_host', 'compute_asset_path',
    'compute_class', 'compute_tags', 'compute_type', 'concat', 'concern', 'concerning', 'concerns', 'config',
    'config_for', 'config_target_version', 'config_when_updating', 'configru', 'configuration',
    'configurations', 'configure', 'configure_rdoc_files', 'configure_sdoc', 'connected?', 'connection',
    'connection_config', 'connection_handler', 'connection_identifier', 'connection_identifiers',
    'connection_pool', 'connection_pool_list', 'connection_pools', 'connection_specification_name',
    'console', 'const_missing', 'constantize', 'constraints', 'consumes?', 'content_columns', 'content_for',
    'content_for?', 'content_length', 'content_mime_type', 'content_security_policy', 'content_security_policy_nonce',
    'content_security_policy_nonce_generator', 'content_security_policy_report_only',
    'content_tag', 'content_type', 'context_class', 'controller', 'controller_class', 'controller_class_for',
    'controller_class_name', 'controller_name', 'controller_path', 'convert', 'convert_key', 'convert_value',
    'converted_arrays', 'cookie_jar', 'cookies', 'copy', 'count', 'count_by_sql', 'country_zones', 'create',
    'create!', 'create_after_upload!', 'create_all', 'create_before_direct_upload!', 'create_current',
    'create_database', 'create_fixtures', 'create_generated_attribute', 'create_join_table',
    'create_migration', 'create_savepoint', 'create_schema', 'create_session', 'create_table',
    'create_with', 'credentials', 'csp_meta_tag', 'csrf_meta_tag', 'csrf_meta_tags', 'ctype', 'current',
    'current_config', 'current_cycle', 'current_database', 'current_hash', 'current_page?', 'current_savepoint_name',
    'current_schema', 'current_version', 'custom', 'cycle', 'dangerous_attribute_method?', 'dangerous_class_method?',
    'dasherize', 'data_source_exists?', 'data_sources', 'database_configuration', 'database_yml',
    'date', 'date?', 'date_field', 'date_field_tag', 'date_select', 'daterange', 'datetime_field', 'datetime_field_tag',
    'datetime_local_field', 'datetime_local_field_tag', 'datetime_select', 'day', 'days', 'days_ago',
    'days_in_month', 'days_in_year', 'days_since', 'days_to_week_start', 'db', 'db_dir', 'debug', 'debug_exception_response_format',
    'debug_hash', 'debug_headers', 'debug_params', 'decode', 'decode_credentials', 'decode_credentials_header',
    'decompose', 'decompress', 'deconstantize', 'decrement', 'decrement!', 'decrement_counter', 'decrypt_and_verify',
    'deep_dup', 'deep_merge', 'deep_merge!', 'deep_stringify_keys', 'deep_stringify_keys!', 'deep_symbolize_keys',
    'deep_symbolize_keys!', 'deep_transform_keys', 'deep_transform_keys!', 'default', 'default_aliases_for_option',
    'default_command_root', 'default_for_option', 'default_form_builder', 'default_generator_root',
    'default_inspect', 'default_options', 'default_scope', 'default_sequence_name', 'default_source_root',
    'default_timezone', 'default_url_options', 'default_value_for_option', 'defaults', 'defer_subscription_confirmation!',
    'defer_subscription_confirmation?', 'define', 'define_attribute', 'define_attribute_method',
    'define_attribute_methods', 'define_callbacks', 'define_model_callbacks', 'define_on', 'delegate',
    'delegate_missing_to', 'delegate_to', 'delete', 'delete_all', 'delete_entry', 'delete_header',
    'delete_if', 'delete_matched', 'delete_operations', 'delete_prefixed', 'delete_session', 'deliver',
    'deliver_later', 'deliver_later!', 'deliver_now', 'deliver_now!', 'demodulize', 'dependency_digest',
    'deprecate', 'deprecate_constant', 'deprecate_methods', 'deprecation_warning', 'desc', 'descendants',
    'descends_from_active_record?', 'deserialize', 'destination', 'destroy', 'destroy!', 'destroy_all',
    'destroyed?', 'destroyed_by_association', 'detach', 'detail_args_for', 'details_for_lookup',
    'determine_default_controller_class', 'determine_default_helper_class', 'determine_default_mailer',
    'dig', 'digest', 'direct', 'direct_descendants', 'dirname', 'dirties_query_cache', 'disable_cache',
    'disable_ddl_transaction!', 'disable_extension', 'disable_query_cache!', 'disable_referential_integrity',
    'disable_test_adapter', 'discard', 'discard!', 'discard_on', 'disconnect', 'disconnect!', 'dispatch',
    'display', 'distance_of_time_in_words', 'distance_of_time_in_words_to_now', 'distinct',
    'document_root_element', 'dom_class', 'dom_id', 'domain', 'done_running', 'done_unloading', 'down',
    'downcase', 'download', 'download_blob_to', 'download_blob_to_tempfile', 'download_chunk',
    'draw', 'driven_by', 'drop', 'drop_all', 'drop_current', 'drop_join_table', 'drop_schema', 'drop_table',
    'dst?', 'dump_schema_cache', 'dup', 'duplicable?', 'duration', 'each', 'each_pair', 'each_record', 'eager_autoload',
    'eager_load', 'eager_load!', 'eager_load_namespaces', 'eager_load_paths', 'eager_loading?',
    'edit_helper', 'email_exists?', 'email_field', 'email_field_tag', 'emails', 'emitted_hidden_id?',
    'empty', 'empty?', 'empty_insert_statement_value', 'emulate_booleans', 'enable_extension',
    'enable_query_cache!', 'enable_test_adapter', 'enable_warnings', 'encode', 'encode!', 'encode_credentials',
    'encode_params', 'encode_with', 'encoding', 'encrypt_and_sign', 'encrypted', 'end_document', 'end_element',
    'end_of_day', 'end_of_hour', 'end_of_minute', 'end_of_month', 'end_of_quarter', 'end_of_week',
    'end_of_year', 'endpoint', 'engine?', 'enlist_fixture_connections', 'enqueue', 'enqueued_jobs',
    'ensure_confirmation_sent', 'enum', 'enumerate', 'env', 'env_config', 'env_filter', 'environment',
    'environment?', 'eof?', 'eql?', 'eql_with_coercion', 'eql_without_coercion', 'error', 'error?', 'error_message',
    'error_number', 'error_wrapping', 'errors', 'escape_bytea', 'escape_javascript', 'escape_once',
    'establish_connection', 'etag', 'etag?', 'etag_matches?', 'event_loop', 'exabyte', 'exabytes', 'except',
    'except!', 'excerpt', 'exclude?', 'exclude_end?', 'exclusive', 'exec_delete', 'exec_insert', 'exec_migration',
    'exec_queries', 'exec_query', 'exec_rollback_db_transaction', 'exec_rollback_to_savepoint',
    'exec_update', 'executable', 'execute', 'execute_command', 'execute_if_updated', 'exist?', 'existent',
    'existent_directories', 'exists?', 'expand_cache_key', 'expand_hash_conditions_for_aggregates',
    'expanded', 'expected_response', 'expire', 'expire_fragment', 'expires_in', 'expires_now', 'explain',
    'extended', 'extending', 'extension', 'extension_enabled?', 'extension_with_delimiter', 'extension_without_delimiter',
    'extensions', 'extify', 'extract!', 'extract_annotations_from', 'extract_domain', 'extract_last_module',
    'extract_options!', 'extract_session_id', 'extract_subdomain', 'extract_subdomains', 'extractable_options?',
    'fallbacks', 'favicon_link_tag', 'fetch', 'fetch_multi', 'fetch_values', 'field_set_tag', 'fields',
    'fields_for', 'fields_for_style?', 'fifth', 'fifth!', 'file_field', 'file_field_tag', 'file_fixture',
    'file_lookup_paths', 'file_path', 'filename', 'filter', 'filter_backtrace', 'filter_proxies',
    'filtered_env', 'filtered_parameters', 'filtered_path', 'filtered_query_string', 'finalized?',
    'find', 'find_all', 'find_all_anywhere', 'find_beginning_of_week!', 'find_by', 'find_by!', 'find_by_sql',
    'find_cmd_and_exec', 'find_each', 'find_file', 'find_in', 'find_in_batches', 'find_or_create_by',
    'find_or_create_by!', 'find_or_initialize_by', 'find_root', 'find_session', 'find_signed',
    'find_template', 'find_tzinfo', 'find_zone', 'find_zone!', 'finder', 'finish', 'finish_with_state',
    'first', 'first!', 'first?', 'fixed_length_secure_compare', 'fixture_file_name', 'fixture_file_upload',
    'fixture_is_cached?', 'fixtures', 'fixtures_path', 'flash', 'flush', 'flush!', 'flush_all!', 'flush_idle_connections!',
    'follow_redirect!', 'font_path', 'font_url', 'for', 'force_ssl', 'force_ssl_redirect', 'foreign_key',
    'foreign_key_exists?', 'foreign_keys', 'foreign_table_exists?', 'foreign_tables', 'forking_env?',
    'form_authenticity_param', 'form_data?', 'form_for', 'form_tag', 'form_with', 'format', 'format_from_path_extension',
    'format_paragraph', 'formats', 'formatted_offset', 'fortnight', 'fortnights', 'forty_two', 'forty_two!',
    'fourth', 'fourth!', 'fragment_cache_key', 'fragment_exist?', 'framework_trace', 'freeze', 'freeze_time',
    'fresh?', 'fresh_when', 'from', 'from_hash', 'from_json', 'from_now', 'from_rails_root', 'from_response',
    'from_trusted_xml', 'from_xml', 'frozen?', 'full_commit!', 'full_message', 'full_messages', 'full_messages_for',
    'full_rollback!', 'full_rollback?', 'full_trace', 'full_url_for', 'fullpath', 'fully_committed?',
    'fully_completed?', 'fully_rolledback?', 'future?', 'gem', 'gem_group', 'gem_version', 'gemfile',
    'gemfile_entry', 'gemspec', 'generate', 'generate_key', 'generate_message', 'generate_method_for_mime',
    'generate_sid', 'generate_test_dummy', 'generate_unique_secure_token', 'generated_path',
    'generator', 'generator_name', 'generators', 'get', 'get_header', 'getgm', 'getlocal', 'getutc', 'gigabyte',
    'gigabytes', 'git', 'github', 'gitignore', 'gmt?', 'gmt_offset', 'gmtime', 'gmtoff', 'grapheme_length',
    'group', 'grouped_collection_select', 'grouped_options_for_select', 'groups', 'h', 'halted_callback',
    'handle_unverified_request', 'handles_encoding?', 'has_and_belongs_to_many', 'has_attribute?',
    'has_basic_credentials?', 'has_changes_to_save?', 'has_header?', 'has_key?', 'has_many', 'has_many_attached',
    'has_named_route?', 'has_one', 'has_one_attached', 'has_secure_password', 'has_secure_token',
    'has_value?', 'hash', 'having', 'head', 'header', 'headers', 'headers_for_direct_upload', 'help', 'helper',
    'helper_attr', 'helper_class', 'helper_method', 'helpers', 'helpers_paths', 'hex?', 'hidden_field',
    'hidden_field_tag', 'hidden_namespaces', 'hide!', 'hide_command!', 'hide_namespace', 'hide_namespaces',
    'highlight', 'hook_for', 'host', 'host_with_port', 'hour', 'hours', 'hstore', 'html?', 'html_document',
    'html_escape', 'html_escape_once', 'html_safe', 'html_safe?', 'http_auth_salt', 'http_basic_authenticate_with',
    'http_cache_forever', 'httpdate', 'https!', 'https?', 'human', 'human_attribute_name', 'human_name',
    'humanize', 'id', 'id?', 'id_before_type_cast', 'id_in_database', 'id_was', 'identified?', 'identified_by',
    'identify', 'ids', 'if_modified_since', 'if_none_match', 'if_none_match_etags', 'ignored_columns',
    'image', 'image?', 'image_alt', 'image_path', 'image_submit_tag', 'image_tag', 'image_url', 'in', 'in?',
    'in_batches', 'in_char_class?', 'in_clause_length', 'in_groups', 'in_groups_of', 'in_milliseconds',
    'in_time_zone', 'include?', 'included', 'includes', 'increment', 'increment!', 'increment_counter',
    'indent', 'indent!', 'index', 'index_algorithms', 'index_by', 'index_exists?', 'index_helper', 'index_name_exists?',
    'index_name_length', 'indexes', 'indexes_per_table', 'inet', 'inflections', 'inheritable_copy',
    'inheritance_column', 'inherited', 'init_with', 'initialize_copy', 'initialize_dup', 'initialize_load_schema_monitor',
    'initialize_sid', 'initialized?', 'initializer', 'initializers', 'initializers_chain', 'initializers_for',
    'inline', 'inquiry', 'insert', 'insert_after', 'insert_before', 'insert_fixture', 'insert_fixtures',
    'insert_fixtures_set', 'inside_template', 'inside_template?', 'inspect', 'install_executor_hooks',
    'instance', 'instance_method_already_implemented?', 'instance_values', 'instance_variable_names',
    'instantiate', 'instantiate_all_loaded_fixtures', 'instantiate_fixtures', 'instrument',
    'instrumenter', 'integration_session', 'internal?', 'internal_metadata_table_name', 'internal_methods',
    'interval', 'invalid?', 'inverse_of', 'invoke', 'invoke_callback', 'ip', 'ips_from', 'irregular', 'is_a?',
    'is_missing?', 'is_utc?', 'isdst', 'isolate_namespace', 'j', 'javascript_include_tag', 'javascript_path',
    'javascript_tag', 'javascript_url', 'javascripts', 'job_or_instantiate', 'joined_includes_values',
    'joins', 'joins_per_query', 'js_template', 'json_escape', 'jsonb', 'keep', 'keep_if', 'key', 'key?', 'key_generator',
    'key_len', 'key_matcher', 'keys', 'kilobyte', 'kilobytes', 'kind', 'kind_of?', 'klass', 'l', 'label', 'label_tag',
    'last', 'last!', 'last?', 'last_inserted_id', 'last_modified', 'last_modified?', 'last_month', 'last_quarter',
    'last_week', 'last_weekday', 'last_year', 'layout', 'lease', 'left_joins', 'left_outer_joins', 'length',
    'lib', 'license', 'limit', 'line', 'link_to', 'link_to_if', 'link_to_unless', 'link_to_unless_current',
    'listen', 'listeners_for', 'listening?', 'load', 'load_config_initializer', 'load_console', 'load_defaults',
    'load_generators', 'load_interlock', 'load_paths', 'load_records', 'load_runner', 'load_schema_current',
    'load_schema_if_pending!', 'load_seed', 'load_session', 'load_target', 'load_tasks', 'loaded?',
    'loading', 'local', 'local?', 'local_assigns', 'local_to_utc', 'localize', 'locals_for', 'localtime',
    'lock', 'lock!', 'locking_column', 'locking_enabled?', 'log', 'log_error', 'log_subscribers', 'logged',
    'logger', 'logger_outputs_to?', 'longblob', 'longtext', 'lookup', 'lookup_ancestors', 'lookup_by_extension',
    'lookup_context', 'lookup_paths', 'lookup_store', 'lseg', 'ltree', 'macaddr', 'mail', 'mail_to', 'mailer',
    'mailer_class', 'mailer_name', 'make_response!', 'many?', 'mark_for_destruction', 'mark_for_same_origin_verification!',
    'marked_for_destruction?', 'marked_for_same_origin_verification?', 'marshal_dump', 'marshal_load',
    'masked_authenticity_token', 'master_key', 'match', 'match?', 'matches?', 'mattr_accessor', 'mattr_reader',
    'mattr_writer', 'max_identifier_length', 'maximum', 'mb_chars', 'media_type', 'mediumblob', 'mediumtext',
    'megabyte', 'megabytes', 'member', 'member?', 'merge', 'merge!', 'merge_default_headers', 'message',
    'message_verifier', 'metadata', 'method', 'method_added', 'method_missing', 'method_symbol', 'midday',
    'middle_of_day', 'middleware', 'midnight', 'migrate', 'migration_template', 'migrations_paths',
    'minimum', 'minus_with_coercion', 'minus_without_coercion', 'minus_without_duration', 'minute',
    'minutes', 'missing?', 'missing_name', 'missing_name?', 'model_name', 'model_resource_name', 'module_namespacing',
    'modules_for_helpers', 'mon_enter', 'monday', 'money', 'month', 'month_field', 'month_field_tag',
    'months', 'months_ago', 'months_since', 'mount', 'mountable_engine?', 'ms', 'multiple_of?', 'mute',
    'mutool_exists?', 'mutool_path', 'name', 'namespace', 'namespaced?', 'namespaced_class_path',
    'namespaced_path', 'native_database_types', 'negative?', 'negotiate_format', 'negotiate_mime',
    'nested', 'nested_under_indifferent_access', 'new', 'new_constants', 'new_helper', 'new_record?',
    'new_session', 'next_day', 'next_migration_number', 'next_month', 'next_occurring', 'next_quarter',
    'next_sequence_value', 'next_week', 'next_weekday', 'next_year', 'nil?', 'no_color!', 'no_routes',
    'no_touching', 'no_touching?', 'non_xhr_javascript_response?', 'nonce', 'none', 'none?', 'noon',
    'normalize', 'normalize_action_path', 'normalize_name', 'normalize_path', 'not', 'not_modified?',
    'notice', 'now', 'now_is_loaded?', 'nsec', 'nullify!', 'num_waiting', 'number_field', 'number_field_tag',
    'number_to_currency', 'number_to_delimited', 'number_to_human', 'number_to_human_size',
    'number_to_percentage', 'number_to_phone', 'number_to_rounded', 'number_with_delimiter',
    'number_with_precision', 'numrange', 'object', 'offset', 'oid', 'on_cdata_block', 'on_characters',
    'on_end_document', 'on_end_element', 'on_load', 'on_start_document', 'on_start_element', 'on_subscribe',
    'on_unsubscribe', 'on_weekday?', 'on_weekend?', 'one?', 'only', 'opaque', 'open', 'open_session', 'operations',
    'opt_parser', 'optimize_indentation', 'optimize_routes_generation?', 'option_groups_from_collection_for_select',
    'optional_port', 'options_for_select', 'options_from_collection_for_select', 'options_include_default?',
    'or', 'order', 'ordinal', 'ordinalize', 'original_concat', 'original_fullpath', 'original_url', 'overlaps?',
    'pack_graphemes', 'package_json', 'param_key', 'parameter_filter', 'parameter_filter_for',
    'parameterize', 'parameters', 'params', 'params_array_from', 'parent', 'parent_name', 'parent_of?',
    'parents', 'parse', 'parse!', 'parse_data_with_trailing_star', 'parse_error', 'parse_trailing_star',
    'parsed_body', 'parser', 'password_field', 'password_field_tag', 'past?', 'patch', 'path', 'path_for',
    'path_parameters', 'path_to_asset', 'path_to_audio', 'path_to_font', 'path_to_image', 'path_to_javascript',
    'path_to_stylesheet', 'path_to_video', 'paths', 'pattern', 'pdftoppm_exists?', 'pdftoppm_path',
    'per_form_csrf_token', 'perform', 'perform_action', 'perform_enqueued_jobs', 'perform_later',
    'perform_now', 'performed?', 'performed_jobs', 'period', 'period_for_local', 'period_for_utc',
    'periodically', 'permanent', 'permit', 'permit!', 'permit_concurrent_loads', 'permitted?', 'persisted?',
    'petabyte', 'petabytes', 'phone_field', 'phone_field_tag', 'pluck', 'plugin_rails_init', 'plugin_rails_options',
    'plugin_rails_replace_reporters', 'plugin_types', 'plural', 'plural_file_name', 'plural_name',
    'plural_route_name', 'plural_table_name', 'pluralize', 'pluralize_table_names', 'pluralize_table_names?',
    'point', 'poll', 'polygon', 'polymorphic_name', 'polymorphic_path', 'polymorphic_url', 'port', 'port_string',
    'positive?', 'post', 'postgresql_version', 'prefetch_primary_key?', 'prefix', 'preload', 'preload_link_tag',
    'prepare!', 'prepare_destination', 'prepend', 'prepend_after_action', 'prepend_around_action',
    'prepend_before_action', 'prepend_view_path', 'prepended', 'presence', 'presence_in', 'present?',
    'pretty_print', 'prev_day', 'prev_month', 'prev_occurring', 'prev_quarter', 'prev_week', 'prev_weekday',
    'prev_year', 'preview', 'preview_name', 'previewable?', 'previous_changes', 'primary_key', 'primary_key_prefix_type',
    'primary_keys', 'print_generators', 'print_list', 'printing_commands', 'priority', 'process',
    'process_action', 'processed', 'processed?', 'proper_table_name', 'property', 'protect_against_forgery?',
    'protect_from_forgery', 'protected_environments', 'protocol', 'provide', 'proxy_association',
    'proxy_class', 'prune', 'pruning?', 'public_compute_asset_path', 'public_directory', 'public_namespaces',
    'public_path', 'publish', 'pubsub', 'pubsub_adapter', 'purge', 'purge_all', 'purge_current', 'purge_later',
    'push', 'put', 'query', 'query_attribute', 'query_cache_enabled', 'query_parameter_names', 'query_parameters',
    'queue_adapter', 'queue_adapter_for_test', 'queue_adapter_name', 'queue_as', 'queue_name',
    'queue_with_priority', 'quote', 'quote_column_name', 'quote_schema_name', 'quote_string', 'quote_table_name',
    'quote_table_name_for_assignment', 'quoted_date', 'quoted_false', 'quoted_primary_key',
    'quoted_table_name', 'quoted_true', 'rack_app', 'radio_button', 'radio_button_tag', 'rails_command',
    'rails_root', 'rails_version', 'railtie_name', 'railties', 'raise', 'raise_validation_error',
    'rake', 'rake_tasks', 'rakefile', 'range_field', 'range_field_tag', 'raw', 'raw_connection', 'raw_host_with_port',
    'raw_params', 'raw_post', 'read', 'read_attribute', 'read_attribute_before_type_cast', 'read_entry',
    'read_fragment', 'read_multi', 'read_multi_entries', 'read_store_attribute', 'readable_inspect',
    'readme', 'readonly', 'readonly!', 'readonly?', 'readonly_attributes', 'real_csrf_token', 'reap',
    'receive', 'reconnect!', 'record', 'record_key_for_dom_id', 'recreate_database', 'redefine_method',
    'redefine_singleton_method', 'redirect', 'redirect_back', 'redirect_resource_name', 'redirect_to',
    'redirect_to_url', 'redis', 'ref', 'references', 'reflect_on_aggregation', 'reflect_on_all_aggregations',
    'reflect_on_all_associations', 'reflect_on_all_autosave_associations', 'reflect_on_association',
    'reflections', 'refresh', 'register', 'register_alias', 'register_callback', 'register_encoder',
    'register_hook', 'register_interceptor', 'register_interceptors', 'register_observer', 'register_observers',
    'register_preview_interceptor', 'register_preview_interceptors', 'register_task', 'regular_class_path',
    'regular_update', 'regular_writer', 'reject', 'reject!', 'reject_unauthorized_connection',
    'release_connection', 'release_savepoint', 'release_unload_lock!', 'reload', 'reload!', 'reload_routes!',
    'remote_connections', 'remote_ip', 'remove', 'remove!', 'remove_belongs_to', 'remove_channel',
    'remove_column', 'remove_columns', 'remove_connection', 'remove_filters!', 'remove_foreign_key',
    'remove_hook_for', 'remove_index', 'remove_possible_method', 'remove_possible_singleton_method',
    'remove_reference', 'remove_references', 'remove_renderer', 'remove_silencers!', 'remove_subscriber',
    'remove_timestamps', 'rename', 'rename_column', 'rename_index', 'rename_key', 'rename_table',
    'render', 'render_body', 'render_collection', 'render_count', 'render_partial', 'render_template',
    'render_to_body', 'render_to_string', 'rendered_format', 'rendered_views', 'reorder', 'reorder_characters',
    'replace', 'report_uri', 'represent_boolean_as_integer', 'representable?', 'representation',
    'reqs', 'request', 'request_authenticity_tokens', 'request_http_basic_authentication', 'request_http_digest_authentication',
    'request_http_token_authentication', 'request_id', 'request_method', 'request_method_symbol',
    'request_parameters', 'require', 'require_application!', 'require_application_and_environment!',
    'require_dependency', 'require_engine', 'require_environment!', 'require_sri_for', 'require_unload_lock!',
    'required', 'requires_reloading?', 'rescue_from', 'rescue_template', 'rescue_with_handler',
    'reset', 'reset!', 'reset_body!', 'reset_cache', 'reset_callbacks', 'reset_column_information',
    'reset_counters', 'reset_cycle', 'reset_locking_column', 'reset_runtime', 'reset_sequence!',
    'reset_session', 'resets', 'resolve', 'resource', 'resources', 'resources_path_names', 'respond_to',
    'respond_to?', 'respond_to_missing?', 'respond_to_without_attributes?', 'response', 'response_body',
    'response_code', 'response_parser', 'restart', 'restore_attributes', 'result', 'retrieve_connection',
    'retrieve_connection_pool', 'retry_job', 'retry_on', 'reverse', 'reverse_merge', 'reverse_merge!',
    'reverse_order', 'reverse_update', 'reversible', 'revert', 'reverting?', 'rewhere', 'rewind', 'rewrite_param_values',
    'rollback', 'rollback!', 'rollback_db_transaction', 'rollback_to_savepoint', 'rolledback?',
    'root', 'route', 'route_for', 'route_key', 'route_url', 'routes', 'ruby_version', 'run', 'run!', 'run_callbacks',
    'run_generator', 'run_in_isolation', 'run_in_transaction?', 'run_initializers', 'run_interlock',
    'run_load_hooks', 'runner', 'running', 'runtime', 'safe_concat', 'safe_constantize', 'safe_get',
    'safe_join', 'sandbox', 'sandbox?', 'sanitize', 'sanitize_css', 'sanitize_limit', 'sanitize_sql',
    'sanitize_sql_array', 'sanitize_sql_for_assignment', 'sanitize_sql_for_conditions', 'sanitize_sql_for_order',
    'sanitize_sql_hash_for_assignment', 'sanitize_sql_like', 'sanitized', 'save', 'save!', 'saved_change_to_attribute',
    'saved_change_to_attribute?', 'saved_changes', 'saved_changes?', 'say', 'say_with_time', 'schema_exists?',
    'schema_file', 'schema_migrations_table_name', 'schema_names', 'schema_search_path', 'scope',
    'scope_for', 'scope_for_create', 'scoping', 'search_field', 'search_field_tag', 'sec_fraction',
    'second', 'second!', 'second_to_last', 'second_to_last!', 'seconds', 'seconds_since_midnight',
    'seconds_to_utc_offset', 'seconds_until_end_of_day', 'secret_key_base', 'secret_token',
    'secrets', 'section', 'section_title', 'secure_compare', 'seed_loader', 'select', 'select!', 'select_all',
    'select_date', 'select_datetime', 'select_day', 'select_hour', 'select_minute', 'select_month',
    'select_one', 'select_rows', 'select_second', 'select_tag', 'select_time', 'select_value', 'select_values',
    'select_year', 'send_async', 'send_data', 'send_early_hints', 'send_file', 'sending!', 'sending?',
    'sent!', 'sent?', 'sequence_name', 'serial', 'serial_sequence', 'serializable_hash', 'serialize',
    'serve', 'server_port', 'server_software', 'service_delete', 'service_delete_prefixed', 'service_download',
    'service_exist', 'service_headers_for_direct_upload', 'service_streaming_download', 'service_upload',
    'service_url', 'service_url_for_direct_upload', 'session', 'session_store', 'set', 'set_application_directory!',
    'set_callback', 'set_content_type', 'set_defaults', 'set_environment', 'set_environment!',
    'set_fixture_class', 'set_header', 'set_logger', 'set_member_mappings_for_resource', 'set_migration_assigns!',
    'set_standard_conforming_strings', 'set_state', 'setup', 'setup_controller_request_and_response',
    'setup_fixture_accessors', 'setup_fixtures', 'setup_horo_variables', 'setup_with_controller',
    'shallow', 'shallow?', 'sharing', 'show', 'show_detailed_exceptions?', 'show_helper', 'show_variable',
    'shutdown', 'signed', 'signed_id', 'signed_or_encrypted', 'silence', 'silence!', 'silence_redefinition_of_method',
    'silence_warnings', 'simple_format', 'since', 'singular', 'singular_name', 'singular_route_key',
    'singular_route_name', 'singular_table_name', 'singularize', 'size', 'skip_after_action', 'skip_around_action',
    'skip_before_action', 'skip_callback', 'skip_forgery_protection', 'skip_parameter_encoding',
    'slice', 'slice!', 'sorted_groups', 'source_extracts', 'source_root', 'split', 'sql', 'sql_query_length',
    'sql_type', 'squish', 'squish!', 'ssl?', 'stale?', 'stale_session_check!', 'standard_port', 'standard_port?',
    'start', 'start_document', 'start_element', 'start_exclusive', 'start_processing', 'start_running',
    'start_sharing', 'start_unloading', 'started_request_message', 'stat', 'statistics', 'stats',
    'status_code', 'status_code_for_exception', 'status_message', 'sti_name', 'stop', 'stop_all_streams',
    'stop_exclusive', 'stop_sharing', 'storage', 'store', 'store_accessor', 'store_inherited', 'stored_attributes',
    'stream_for', 'stream_from', 'strftime', 'strict_mode?', 'stringify_array', 'stringify_keys',
    'stringify_keys!', 'strip_heredoc', 'strip_links', 'strip_tags', 'strong_etag?', 'strptime', 'structure_dump',
    'structure_dump_flags', 'structure_load', 'structure_load_flags', 'stylesheet_link_tag',
    'stylesheet_path', 'stylesheet_url', 'stylesheets', 'subclasses', 'subdomain', 'subdomains', 'submit',
    'submit_tag', 'subscribe', 'subscribe_to_channel', 'subscribed', 'subscribers', 'subscription_confirmation_sent?',
    'subscription_rejected?', 'subsec', 'success?', 'suffix', 'sum', 'sunday', 'supports_advisory_locks?',
    'supports_bulk_alter?', 'supports_comments?', 'supports_comments_in_create?', 'supports_datetime_with_precision?',
    'supports_ddl_transactions?', 'supports_explain?', 'supports_expression_index?', 'supports_extensions?',
    'supports_foreign_keys?', 'supports_foreign_keys_in_create?', 'supports_foreign_tables?',
    'supports_index_sort_order?', 'supports_indexes_in_create?', 'supports_json?', 'supports_materialized_views?',
    'supports_multi_insert?', 'supports_partial_index?', 'supports_path?', 'supports_pgcrypto_uuid?',
    'supports_ranges?', 'supports_savepoints?', 'supports_streaming?', 'supports_transaction_isolation?',
    'supports_validate_constraints?', 'supports_views?', 'supports_virtual_columns?', 'suppress',
    'suppress_messages', 'swap', 'swapcase', 'swapcase_mapping', 'symbolize_keys', 'symbolize_keys!',
    'symbols', 'system_test', 't', 'table_alias_for', 'table_alias_length', 'table_comment', 'table_exists?',
    'table_name', 'table_name_length', 'table_name_prefix', 'table_name_suffix', 'table_options',
    'table_rows', 'tableize', 'tables', 'tag', 'tagged', 'take', 'take!', 'take_failed_screenshot', 'take_screenshot',
    'target', 'target_version', 'teardown', 'teardown_fixtures', 'telephone_field', 'telephone_field_tag',
    'tempdir', 'template', 'template_exists?', 'terabyte', 'terabytes', 'test', 'test_dummy_assets',
    'test_dummy_clean', 'test_dummy_config', 'test_errors_aref', 'test_model_naming', 'test_order',
    'test_persisted?', 'test_to_key', 'test_to_param', 'test_to_partial_path', 'tests', 'text?', 'text_area',
    'text_area_tag', 'text_field', 'text_field_tag', 'third', 'third!', 'third_to_last', 'third_to_last!',
    'thread_cattr_accessor', 'thread_mattr_accessor', 'tidy_bytes', 'time', 'time_ago_in_words',
    'time_field', 'time_field_tag', 'time_select', 'time_tag', 'time_zone_options_for_select',
    'time_zone_select', 'timer', 'timestamps', 'tinyblob', 'tinytext', 'titlecase', 'titleize', 'tmp', 'to',
    'to_a', 'to_ary', 'to_complete', 'to_date', 'to_datetime', 'to_default_s', 'to_dep_map', 'to_f', 'to_formatted_s',
    'to_h', 'to_hash', 'to_html', 'to_i', 'to_json', 'to_key', 'to_model', 'to_options', 'to_options!', 'to_param',
    'to_partial_path', 'to_path', 'to_prepare', 'to_prepare_blocks', 'to_query', 'to_r', 'to_run', 'to_s',
    'to_sentence', 'to_sql', 'to_str', 'to_sym', 'to_tag', 'to_time', 'to_unsafe_h', 'to_unsafe_hash', 'to_xml',
    'to_yaml_type', 'today', 'today?', 'toggle', 'toggle!', 'token_and_options', 'token_params_from',
    'tomorrow', 'touch', 'traces', 'transaction', 'transaction_isolation_levels', 'transaction_open?',
    'transaction_state', 'transform', 'transform_keys', 'transform_keys!', 'transform_values',
    'transform_values!', 'translate', 'transliterate', 'transmit', 'travel', 'travel_back', 'travel_to',
    'tree', 'truncate', 'truncate_words', 'try', 'try!', 'tsort_each_child', 'tsrange', 'tstzrange', 'tsvector',
    'tv_sec', 'type', 'type_cast', 'type_cast_config_to_boolean', 'type_cast_config_to_integer',
    'type_for_attribute', 'uncached', 'uncountable', 'uncountable?', 'undefine_attribute_methods',
    'underscore', 'unescape', 'unescape_bytea', 'unload_interlock', 'unloading', 'unmask_token', 'unpack_graphemes',
    'unpermitted_parameters', 'unprepared_statement', 'unquoted_false', 'unquoted_true', 'unregister',
    'unscope', 'unscoped', 'unshift', 'unsigned_bigint', 'unsigned_decimal', 'unsigned_float', 'unsigned_integer',
    'unsubscribe', 'unsubscribed', 'until', 'up', 'up_only', 'upcase', 'upcase_first', 'update', 'update!',
    'update_all', 'update_attribute', 'update_attributes', 'update_attributes!', 'update_column',
    'update_columns', 'update_counters', 'update_metadata', 'updated?', 'upgrade_insecure_requests',
    'upload', 'url', 'url_field', 'url_field_tag', 'url_for', 'url_for_direct_upload', 'url_helper_prefix',
    'url_options', 'url_to_asset', 'url_to_audio', 'url_to_font', 'url_to_image', 'url_to_javascript',
    'url_to_stylesheet', 'url_to_video', 'us_zones', 'usage_path', 'use', 'use_accept_header', 'use_insert_returning?',
    'use_renderer', 'use_renderers', 'use_zone', 'usec', 'user_name_and_password', 'uses_transaction',
    'uses_transaction?', 'utc', 'utc?', 'utc_offset', 'utc_to_local', 'uuid', 'uuid_from_hash', 'valid?',
    'valid_accept_header', 'valid_alter_table_type?', 'valid_authenticity_token?', 'valid_message?',
    'valid_per_form_csrf_token?', 'valid_request_origin?', 'validate', 'validate!', 'validate_constraint',
    'validate_digest_response', 'validate_foreign_key', 'validate_nonce', 'validate_secret_key_base',
    'validates', 'validates!', 'validates_absence_of', 'validates_acceptance_of', 'validates_associated',
    'validates_confirmation_of', 'validates_each', 'validates_exclusion_of', 'validates_format_of',
    'validates_inclusion_of', 'validates_length_of', 'validates_numericality_of', 'validates_presence_of',
    'validates_size_of', 'validates_uniqueness_of', 'validates_with', 'validators', 'validators_on',
    'value', 'value?', 'values', 'values_at', 'variable?', 'variant', 'vendor', 'verified', 'verified_request?',
    'verify', 'verify!', 'verify_authenticity_token', 'verify_same_origin_request', 'version',
    'version_control', 'video?', 'video_path', 'video_tag', 'video_url', 'view_assigns', 'view_cache_dependencies',
    'view_cache_dependency', 'view_context', 'view_context_class', 'view_exists?', 'view_paths',
    'view_rendered?', 'views', 'visit_arel_nodes_in', 'visit_arel_nodes_sqlliteral', 'wait', 'warn',
    'watch_namespaces', 'watchable_dirs', 'watchable_files', 'watching?', 'weak_etag?', 'week', 'week_field',
    'week_field_tag', 'weeks', 'weeks_ago', 'weeks_since', 'where', 'where_values_hash', 'will_save_change_to_attribute?',
    'with', 'with_backend', 'with_connection', 'with_database_connections', 'with_default_scope',
    'with_defaults', 'with_defaults!', 'with_fallbacks', 'with_indifferent_access', 'with_local_cache',
    'with_lock', 'with_options', 'with_routing', 'with_scope_level', 'with_warnings', 'without', 'without_modules',
    'word_wrap', 'worker_pool', 'wrap', 'wrap_parameters', 'wrap_with_namespace', 'write', 'write_attribute',
    'write_entry', 'write_fragment', 'write_multi', 'write_session', 'write_store_attribute', 'writes_pending',
    'xhr?', 'xml', 'xml_http_request?', 'xmlschema', 'xor_byte_strings', 'year', 'years', 'years_ago', 'years_since',
    'yesterday', 'yield_shares', 'zone', 'API', 'AbstractAdapter', 'AbstractController', 'AbstractMysqlAdapter',
    'AbstractStore', 'AcceptanceValidator', 'AcceptsMultiparameterTime', 'ActionCable', 'ActionCableHelper',
    'ActionController', 'ActionDispatch', 'ActionMailer', 'ActionNotFound', 'ActionView', 'Actions',
    'ActiveJob', 'ActiveModel', 'ActiveModelHelper', 'ActiveModelInstanceTag', 'ActiveRecord',
    'ActiveRecordConnectionManagement', 'ActiveRecordError', 'ActiveStorage', 'ActiveSupport',
    'AdapterNotFound', 'AdapterNotSpecified', 'AdapterSpecificRegistry', 'After', 'Aggregations',
    'All', 'AllType', 'AlterTable', 'Analyzable', 'AnalyzeJob', 'Analyzer', 'ApiRendering', 'AppBase', 'AppBuilder',
    'Application', 'Array', 'ArrayInquirer', 'AssertionResponse', 'Assertions', 'AssetTagHelper',
    'AssetUrlHelper', 'AssociationRelation', 'AssociationTypeMismatch', 'Associations', 'Async',
    'AsyncAdapter', 'AsyncSubscriberMap', 'AtomFeedHelper', 'Attached', 'Attachment', 'AttributeAssignment',
    'AttributeAssignmentError', 'AttributeDefinition', 'AttributeMethods', 'Attributes', 'Authorization',
    'Autoload', 'AutosaveAssociation', 'AzureStorageService', 'BackburnerAdapter', 'BacktraceCleaner',
    'Base', 'BaseController', 'BaseJob', 'Basic', 'BatchEnumerator', 'Batches', 'Before', 'BeforeTypeCast',
    'Behavior', 'Behaviour', 'Benchmark', 'Benchmarkable', 'BigDecimal', 'BigInteger', 'Binary', 'Bit',
    'Blob', 'BlobsController', 'Boolean', 'Bootstrap', 'Broadcaster', 'Broadcasting', 'Builder', 'Cache',
    'CacheHelper', 'CacheStore', 'Caching', 'CachingKeyGenerator', 'Calculations', 'Callbacks', 'CaptureHelper',
    'ChainedCookieJars', 'Channel', 'Chars', 'CheckPending', 'Class', 'ClassCache', 'ClassMethods', 'ClearTestDeliveries',
    'ClientDisconnected', 'Codepoint', 'Collection', 'CollectionCacheKey', 'CollectionProxy', 'Collector',
    'Column', 'ColumnMethods', 'ColumnNotSerializableError', 'Command', 'CommandRecorder', 'Compatibility',
    'Complex', 'Concern', 'Concerning', 'Concerns', 'Concurrency', 'ConditionalGet', 'Conditionals',
    'ConfigMethods', 'Configurable', 'Configuration', 'ConfigurationError', 'Connection', 'ConnectionAdapters',
    'ConnectionHandler', 'ConnectionHandling', 'ConnectionNotEstablished', 'ConnectionPool',
    'ConnectionPoolConfiguration', 'ConnectionPoolLike', 'ConnectionTimeoutError', 'Console',
    'ConsoleFormatter', 'ConsoleMethods', 'ConstantLookup', 'ContentSecurityPolicy', 'Context',
    'ControllerMethods', 'Conversion', 'CookieStore', 'Cookies', 'Core', 'CounterCache', 'CspHelper',
    'CsrfHelper', 'CurrentAttributes', 'CustomUrlHelper', 'CustomUrls', 'DBConsole', 'DangerousAttributeError',
    'Data', 'DataStreaming', 'DatabaseLimits', 'DatabaseStatements', 'DatabaseTasks', 'Date', 'DateAndTime',
    'DateHelper', 'DateTime', 'Deadlocked', 'DebugExceptions', 'DebugHelper', 'DebugLocks', 'DebugView',
    'Decimal', 'Declarative', 'DecorationRegistration', 'Default', 'DefaultMiddlewareStack', 'DefineCallbacks',
    'DelayedJobAdapter', 'DelegationError', 'Delegator', 'DeliveryMethods', 'Dependencies', 'DeprecatedConstantAccessor',
    'DeprecatedConstantProxy', 'DeprecatedInstanceVariableProxy', 'DeprecatedObjectProxy',
    'Deprecation', 'DeprecationException', 'DescendantsTracker', 'DeserializationError', 'DetailsCache',
    'DetermineIfPreparableVisitor', 'Digest', 'Digestor', 'DirectUploadsController', 'Dirty', 'DisallowedType',
    'DiskController', 'DiskService', 'Dispatcher', 'DoubleRenderError', 'Downloading', 'Duration',
    'DynamicMatchers', 'ERB', 'EagerLoadPolymorphicError', 'EdgeTask', 'Editor', 'EncryptedConfiguration',
    'EncryptedFile', 'Encryptor', 'Engine', 'Enqueuing', 'EntityStore', 'Enum', 'Enumerable', 'EnvironmentMismatchError',
    'Errors', 'EtagWithFlash', 'EtagWithTemplateDigest', 'Event', 'EventedFileUpdateChecker', 'Exception',
    'ExceptionWrapper', 'Exceptions', 'ExclusiveConnectionTimeoutError', 'Execution', 'ExecutionWrapper',
    'Executor', 'Explain', 'FalseClass', 'Fanout', 'File', 'FileFixtures', 'FileHandler', 'FileStore', 'FileSystemResolver',
    'FileUpdateChecker', 'Filename', 'FilterParameters', 'FilterRedirect', 'Filters', 'FindBy', 'FindByBang',
    'FinderMethods', 'Finisher', 'FixtureFile', 'FixtureResolver', 'FixtureSet', 'Flash', 'FlashHash',
    'Float', 'ForbiddenAttributesError', 'ForceSSL', 'Forking', 'FormBuilder', 'FormHelper', 'FormOptionsHelper',
    'FormTagHelper', 'Format', 'Formatter', 'Fragments', 'GCSService', 'GET', 'GemfileEntry', 'Generator',
    'Generators', 'GetIp', 'Gzip', 'Handlers', 'Hash', 'HashBuilder', 'HashWithIndifferentAccess', 'Head',
    'Headers', 'HelperMethods', 'Helpers', 'Html', 'HtmlTableFormatter', 'Http', 'HttpAuthentication',
    'HttpHelpers', 'IO', 'Identifiable', 'Identification', 'IdentityEncoder', 'ImageAnalyzer', 'ImmutableRelation',
    'ImplicitRender', 'Inflections', 'Inflector', 'Info', 'InheritableOptions', 'Inheritance', 'Initializable',
    'Initializer', 'Injected', 'InlineAdapter', 'InlinePreviewInterceptor', 'InstanceMethodsOnActivation',
    'Instrumentation', 'Instrumenter', 'Integer', 'Integration', 'IntegrationTest', 'IntegrityError',
    'Interlock', 'InterlockHook', 'Internal', 'InternalChannel', 'InvalidForeignKey', 'InvalidIdentifiersError',
    'InvalidMessage', 'InvalidNumberError', 'InvalidSignature', 'InvariableError', 'IpSpoofAttackError',
    'IrreversibleMigration', 'IrreversibleOrderError', 'Isolation', 'JSON', 'JavaScriptHelper',
    'Journey', 'Json', 'Kernel', 'KeyGenerator', 'LateAttachmentsProxy', 'Layouts', 'LazilyDefineAttributes',
    'LazyLoadHooks', 'LegacyYamlAdapter', 'Lint', 'Listener', 'Live', 'LiveTestResponse', 'LoadError',
    'LoadInterlockAwareMonitor', 'Loadable', 'LocalCache', 'LocalStore', 'Locals', 'LockWaitTimeout',
    'Locking', 'LogSubscriber', 'Logger', 'LoggerSilence', 'LookupContext', 'MacroReflection', 'Macros',
    'MailHelper', 'Many', 'Mapper', 'MemCacheStore', 'MemoryStore', 'MessageDelivery', 'MessageEncryptor',
    'MessageVerifier', 'Messages', 'MetaStore', 'Metal', 'Method', 'MethodWrapper', 'Middleware', 'MiddlewareStack',
    'MiddlewareStackProxy', 'Migration', 'Mime', 'MimeNegotiation', 'MimeResponds', 'Mimes', 'Minitest',
    'MirrorService', 'MismatchedForeignKey', 'Missing', 'MissingAttributeError', 'MissingContentError',
    'MissingHelperError', 'MissingKeyError', 'MissingRenderer', 'MockLogger', 'Model', 'ModelSchema',
    'Module', 'MountedHelpers', 'MuPDFPreviewer', 'Multibyte', 'MultiparameterAssignmentErrors',
    'Mutable', 'MutexHook', 'MySQL', 'Name', 'NameError', 'Named', 'NamedBase', 'NamedRouteCollection',
    'Naming', 'NestedAttributes', 'NilClass', 'NoDatabaseError', 'NoTouching', 'Node', 'NonInferrableMailerError',
    'NotNullViolation', 'Notifications', 'NullColumn', 'NullLogger', 'NullResolver', 'NullSession',
    'NullStore', 'NullType', 'NumberHelper', 'Numeric', 'NumericWithFormat', 'OID', 'Object', 'One', 'Optimistic',
    'OptimizedUrlHelper', 'Options', 'OrderedHash', 'OrderedOptions', 'OutputSafetyHelper', 'PG',
    'POST', 'ParameterEncoding', 'ParameterFilter', 'ParameterMissing', 'Parameterized', 'Parameters',
    'ParamsWrapper', 'ParseError', 'Parser', 'ParsingError', 'Partial', 'PartialIteration', 'PartialQueryCollector',
    'PartialRenderer', 'Path', 'PathHelper', 'PathRedirect', 'Paths', 'PerExecutionDigestCacheExpiry',
    'PerThreadRegistry', 'PeriodicTimers', 'Persistence', 'Pessimistic', 'PluginBuilder', 'PolymorphicRoutes',
    'PopplerPDFPreviewer', 'PostgreSQL', 'PostgreSQLAdapter', 'PostgreSQLTypeMetadata', 'PredicateBuilder',
    'PreparedStatementCacheExpired', 'PreparedStatementInvalid', 'Preview', 'Previewer', 'Previews',
    'PrimaryKey', 'Process', 'ProtectionMethods', 'ProxyObject', 'PublicExceptions', 'PurgeJob', 'QuAdapter',
    'QueAdapter', 'Query', 'QueryCache', 'QueryCanceled', 'QueryMethods', 'Querying', 'Queue', 'QueueAdapter',
    'QueueAdapters', 'QueueClassicAdapter', 'QueueName', 'QueuePriority', 'Quoting', 'README', 'Rack',
    'RackBody', 'Rails', 'RailsEntityStore', 'RailsMetaStore', 'Railtie', 'Railties', 'Range', 'RangeError',
    'RangeHandler', 'RangeWithBinds', 'RangeWithFormat', 'Rational', 'Raw', 'Read', 'ReadOnlyRecord',
    'ReadonlyAttributes', 'RealTransaction', 'Reaper', 'RecordFetchWarning', 'RecordIdentifier',
    'RecordInvalid', 'RecordNotDestroyed', 'RecordNotFound', 'RecordNotSaved', 'RecordNotUnique',
    'RecordTagHelper', 'Redirecting', 'Redirection', 'Redis', 'RedisCacheStore', 'Reflection', 'RegexCaseComparator',
    'Registration', 'Registry', 'Relation', 'Reloader', 'RemoteConnection', 'RemoteConnections', 'RemoteIp',
    'RenderedViewsCollection', 'Renderer', 'Renderers', 'Rendering', 'RenderingHelper', 'RepoTask',
    'Reporting', 'Representable', 'RepresentationsController', 'Request', 'RequestEncoder', 'RequestForgeryProtection',
    'RequestHelpers', 'RequestId', 'RequestMethods', 'Rescuable', 'Rescue', 'ResetSession', 'Resolver',
    'Resources', 'Response', 'ResponseAssertions', 'ResqueAdapter', 'Result', 'Rollback', 'Root', 'Rotator',
    'Route', 'RouteSet', 'RouteWrapper', 'RoutesHelpers', 'RoutesReloader', 'Routing', 'RoutingAssertions',
    'RoutingUrlFor', 'Runner', 'SSE', 'SSL', 'SafeBuffer', 'SafeConcatError', 'Sanitization', 'SanitizeHelper',
    'SavepointTransaction', 'Savepoints', 'Schema', 'SchemaCache', 'SchemaStatements', 'Scoping',
    'ScreenshotHelper', 'Secrets', 'SecurePassword', 'SecureRandom', 'SecureToken', 'SecurityUtils',
    'Serialization', 'SerializationError', 'SerializationFailure', 'SerializationTypeMismatch',
    'Serializers', 'Server', 'Service', 'Session', 'SetupAndTeardown', 'ShareLock', 'ShowExceptions',
    'SidekiqAdapter', 'SimpleFormatter', 'SmallCache', 'SneakersAdapter', 'SourceAnnotationExtractor',
    'SpawnMethods', 'SqlTypeMetadata', 'StableTask', 'StaleObjectError', 'StaleSessionCheck', 'StatementInvalid',
    'StatementTimeout', 'Static', 'StaticDispatcher', 'Store', 'Strategy', 'Stream', 'StreamEventLoop',
    'Streaming', 'Streams', 'StrictValidationFailed', 'String', 'StringInquirer', 'StrongParameters',
    'SubclassNotFound', 'Subprocess', 'Subscriber', 'SubscriberMap', 'SubscriptionAdapter', 'SuckerPunchAdapter',
    'SuppressedSummaryReporter', 'Suppressor', 'Symbol', 'SystemTestCase', 'SystemTesting', 'Table',
    'TableDefinition', 'TagHelper', 'TaggedLoggerProxy', 'TaggedLogging', 'Task', 'Tasks', 'Template',
    'TemplateAssertions', 'TestAdapter', 'TestCase', 'TestController', 'TestFixtures', 'TestHelper',
    'TestHelpers', 'TestProcess', 'TestQueueAdapter', 'TestRequest', 'TestResponse', 'Testing', 'Tests',
    'TextHelper', 'Time', 'TimeHelpers', 'TimeValue', 'TimeWithZone', 'TimeZone', 'TimeZoneConversion',
    'Timestamp', 'Timezone', 'Token', 'TooManyRecords', 'TouchLater', 'TransactionIsolationError',
    'TransactionRollbackError', 'TransactionState', 'Transactions', 'Translation', 'TranslationHelper',
    'TrueClass', 'Type', 'TypeConflictError', 'Types', 'URI', 'URL', 'UUID', 'UnauthorizedError', 'Uncountables',
    'UnfilteredParameters', 'Unicode', 'UnicodeDatabase', 'Unknown', 'UnknownAttributeError', 'UnknownAttributeReference',
    'UnknownPrimaryKey', 'UnpermittedParameters', 'UnpreviewableError', 'UnprocessedError',
    'UnrepresentableError', 'Updater', 'UploadedFile', 'UrlFor', 'UrlHelper', 'UrlOptions', 'Util', 'VERSION',
    'ValidationError', 'Validations', 'Validator', 'Value', 'ValueTooLong', 'Variant', 'Variation', 'VerbMatchers',
    'Verifier', 'Version', 'VideoAnalyzer', 'VideoPreviewer', 'ViewPaths', 'WatchStack', 'WhereChain',
    'Worker', 'WrappedDatabaseException', 'Write', 'XMLConverter', 'XmlMini', 'Zones'
]
# ------------------------------- KEYWORD -------------------------------------------------------------------------

class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'deoplete-rails'
        self.filetypes = ['ruby']
        self.mark = '[Rails]'
        self.rank = 1

    def get_complete_position(self, context):
        m = re.search('[a-zA-Z0-9_?!]*$', context['input'])
        return m.start() if m else -1

    def gather_candidates(self, context):
        try:
            dic = rails_keywords
            return dic
        except Exception:
            traceback.print_exc()
